project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - before_you_come.qmd
    - slides.qmd
    - flowcharts.qmd
    - 05_miad.qmd
    - 06_cad.qmd
    - 07_mcad.qmd
    - slides/hands_on.qmd
  resources:
    - slides/*.pdf

website:
  title: "Matching Methods for Multilevel Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: before_you_come.qmd
        text: Before you come
      - href: slides.qmd
        text: Slides
      - href: 05_miad.qmd
        text: "Ch5: MIAD"
      - href: 06_cad.qmd
        text: "Ch6: CAD"
      - href: 07_mcad.qmd
        text: "Ch7: MCAD"
      - href: flowcharts.qmd
        text: Flowcharts
    right:
      - icon: github
        href: https://github.com/alberto-guzman/multilevel-matching-workshop

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-tools: true
    code-annotations: below

execute:
  warning: false
  message: false
  freeze: auto
