project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - before_you_come.qmd
    - follow_along.qmd
    - flowcharts.qmd
    - 05_miad.qmd
    - 06_cad.qmd
    - 07_mcad.qmd

website:
  title: "Matching Methods for Multilevel Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: before_you_come.qmd
        text: Before you come
      - href: follow_along.qmd
        text: Follow-along
      - href: flowcharts.qmd
        text: Flowcharts
      - href: 05_miad.qmd
        text: "Ch5: MIAD"
      - href: 06_cad.qmd
        text: "Ch6: CAD"
      - href: 07_mcad.qmd
        text: "Ch7: MCAD"
    right:
      - icon: github
        href: https://github.com/alberto-guzman/multilevel-matching-workshop
      - text: Handbook
        href: https://albertoguz.quarto.pub/draft-propensity-score-matching-in-multilevel-educational-settings

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-tools: true
    code-annotations: below

execute:
  warning: false
  message: false
  freeze: auto
